import assert from "node:assert/strict";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import { execFileSync } from "node:child_process";

const root = path.resolve(import.meta.dirname, "..");
const spec = "config/world-items/cafe-bar-stool-01.json";
const schemaPath = "config/astra-build-request.schema.json";
const policyPath = "config/astra-toolchain-policy.json";
const run = () => JSON.parse(execFileSync(process.execPath, ["scripts/compile-astra-build-request.mjs", spec], { cwd: root, encoding: "utf8" }));
const first = run();
const second = run();
const schema = JSON.parse(fs.readFileSync(path.join(root, schemaPath), "utf8"));
const policy = JSON.parse(fs.readFileSync(path.join(root, policyPath), "utf8"));

assert.deepEqual(first, second, "same canonical spec must compile deterministically");
assert.equal(first.$schema, schemaPath);
assert.equal(schema.$schema, "https://json-schema.org/draft/2020-12/schema");
assert.equal(schema.properties.schema_version.const, first.schema_version);
assert.equal(schema.properties.kind.const, first.kind);
assert.ok(schema.required.every((key) => Object.hasOwn(first, key)), "request must contain every schema-required top-level field");
assert.equal(first.kind, "astra_build_request");
assert.equal(first.source.canonical_spec, spec);
assert.equal(first.intent.id, "cafe-bar-stool-01");
assert.deepEqual(first.intent.dimensions_m, [0.42, 0.42, 0.74]);
assert.equal(first.constraints.generation_method, "procedural");
assert.equal(first.constraints.manual_mesh_edit_as_authority, false);
assert.ok(Number.isInteger(first.constraints.deterministic_seed));
assert.equal(first.verification.independent_static_gate, true);
assert.equal(first.verification.visual_loop.repair_on_fail, true);
assert.equal(first.verification.platforms.android, "UNVERIFIED");
assert.equal(first.toolchain_policy.source, policyPath);
assert.equal(first.toolchain_policy.production_tier, policy.default_production_tier);
assert.deepEqual(first.toolchain_policy.control_priority, policy.control_priority);
assert.equal(first.toolchain_policy.one_responsibility_one_authority, policy.one_responsibility_one_authority);
assert.deepEqual(Object.keys(policy.tiers).sort(), ["P0", "P1", "P2", "P3"]);
assert.equal(policy.tiers.P0.production_eligible, true);
assert.equal(policy.tiers.P1.production_eligible, true);
assert.equal(policy.tiers.P2.production_eligible, false);
assert.equal(policy.tiers.P3.production_eligible, false);
assert.equal(policy.tiers.P2.experimental, true);
assert.equal(policy.tiers.P3.experimental, true);
assert.ok(first.constraints.license.provenance.length > 0);
assert.match(first.source.sha256, /^[0-9a-f]{64}$/);

const out = path.join(os.tmpdir(), `vrmine-astra-${process.pid}.json`);
execFileSync(process.execPath, ["scripts/compile-astra-build-request.mjs", spec, out], { cwd: root });
assert.deepEqual(JSON.parse(fs.readFileSync(out, "utf8")), first);
fs.rmSync(out, { force: true });
console.log("astra build request contract: PASS");
