#!/usr/bin/env python3
"""Build public landing-page status from committed verification evidence."""
from __future__ import annotations

import json
from datetime import datetime, timezone
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUTPUT = ROOT / "site" / "status.json"

GATES = {
    "g1": ROOT / "Assets/KafkaMade/VRMine/Verification/LatestBoardGamesVerification.txt",
    "g2": ROOT / "Assets/KafkaMade/VRMine/Verification/LatestBoardGamesRuntimeVerification.txt",
    "g3": ROOT / "Assets/KafkaMade/VRMine/Verification/LatestVRChatBuildAndTest.txt",
    "g4": ROOT / "Assets/KafkaMade/VRMine/Verification/LatestUploadReadiness.txt",
}


def read_gate(path: Path) -> dict[str, str]:
    if not path.exists():
        return {"status": "MISSING", "summary": "Evidence file is missing."}
    text = path.read_text(encoding="utf-8-sig").strip()
    if "Result: PASS" in text:
        status = "PASS"
    elif "Result: BLOCKED" in text or "Status: BLOCKED" in text:
        status = "BLOCKED"
    elif "Result: FAIL" in text:
        status = "FAIL"
    else:
        status = "PENDING"
    summary = next((line for line in text.splitlines() if line.startswith(("Reason:", "Status:"))), text.splitlines()[0] if text else "No evidence.")
    return {"status": status, "summary": summary}


def main() -> None:
    payload = {
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "commit": "generated by GitHub Pages workflow",
        "gates": {name: read_gate(path) for name, path in GATES.items()},
    }
    payload["release_status"] = payload["gates"]["g4"]["status"]
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(json.dumps(payload, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    print(f"wrote {OUTPUT.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
